### ISSUE TITLE
[com.google.fonts/check/fontvalidator] ERRORs if FontValidator is not installed

### ISSUE THREAD

**Issue by miguelsousa** [miguelsousa/openbakery#30]
## Observed behaviour

If FontValidator is not installed, `com.google.fonts/check/fontvalidator` fails with two ERROR messages.

<img width="1229" alt="fontval" src="https://github.com/miguelsousa/openbakery/assets/2119742/787d3a62-5a80-4df1-a29e-94a7df12b07b">

## Expected behaviour

The first ERROR should be converted into a FAIL, because there's nothing wrong with `openbakery` itself.
The second ERROR needs to be fixed; it's caused by trying to run FontValidator before checking if it's available.

## Resources and steps needed to reproduce

Install `openbakery` and run,

    openbakery check-fontval data/test/source-sans-pro/OTF/SourceSansPro-Regular.otf

**Comment by felipesanches** [comment]
> The first ERROR should be converted into a FAIL, because there's nothing wrong with `openbakery` itself.

* A **FAIL** is a problem in a font.
* An **ERROR** is a bug in the program or a bad setup, such as a missing third-party tool in the system.

When FontValidator is not installed, it is treated as a bad system setup, thus, it is classified as an **ERROR**. It is not a **FAIL** because it is not a font problem.

**Comment by miguelsousa** [comment]
I think neither status is quite right for conveying that a tool or package needed for running a check is missing. However,
1. there's a [precedent for yielding FAIL when a package is missing](https://github.com/googlefonts/fontbakery/blob/a328639bf3239bd628643ba388c1386c77a7c590/Lib/fontbakery/profiles/googlefonts.py#L7089), and 
2. the check-run ends with a [message that instructs users to report ERROR statuses](https://github.com/googlefonts/fontbakery/blob/a328639bf3239bd628643ba388c1386c77a7c590/Lib/fontbakery/reporters/terminal.py#L630-L631).

So even though FAIL is commonly regarded as a font problem, it seems appropriate (and less harsh) to use when a check cannot be run. I suppose SKIP could be used as well if we interpret it as "the conditions for running the check have not been met", but that would result in a silent failure.

**Comment by miguelsousa** [comment]
> * A **FAIL** is a problem in a font.
> * An **ERROR** is a bug in the program or a bad setup, such as a missing third-party tool in the system.

That division is sensible for a programmer, I think.
Instead, my goal is to aim toward a more user-centric organization of the statuses. As such, I see them fitting into two main categories:

1. The check didn't run in its entirety; it exited abruptly or unexpectedly. There is nothing a user can do on their end to fix the failure. The only action is for the user to report the problem. Yield **ERROR** in such scenario.
2. The check ran in its entirety. The user is able to address any check failures on their own, without requiring the tool's codebase to be updated. In such scenario, yield all appropriate statuses except ERROR.

I think this way there's a clear distinction between when a tool-run completes in an expected way and when it doesn't. The benefit for users is that overtime they'll know that an ERROR result is something that's beyond their control, unlike all the other check results.

**Comment by graphicore** [comment]
> The check ran in its entirety. The user is able to address any check failures on their own, without requiring the tool's codebase to be updated. In such scenario, yield all appropriate statuses except ERROR.

The part where the user is able to address a bad setup of the system, such as installing a missing software in the system,  on their own is requiring a very specific type of a user. E.g. the machine must be administered by the user, the user must be allowed to install software on their own and the user must be skilled to do so. I've seen organizations where that is not a given, and I.T. would have to approve all the executed software. Or think of a remote deployment on a server. To aid the the role that is setting up the environment, it would be easier to yield ERROR, it sticks out and signals brightly that the tool is not completely ready. If it can't be fixed in the font, which is the part that the "user" is controlling usually it should not be a FAIL.

> 1. there's a [precedent for yielding FAIL when a package is missing](https://github.com/googlefonts/fontbakery/blob/a328639bf3239bd628643ba388c1386c77a7c590/Lib/fontbakery/profiles/googlefonts.py#L7089), and

Maybe that precedence should be fixed instead. Also, maybe we need a way beyond status messages to handle these cases. Configuration could be used to switch statuses or to exclude checks.

> 2. the check-run ends with a [message that instructs users to report ERROR statuses](https://github.com/googlefonts/fontbakery/blob/a328639bf3239bd628643ba388c1386c77a7c590/Lib/fontbakery/reporters/terminal.py#L630-L631).

That could be reworded easily.

> I think this way there's a clear distinction between when a tool-run completes in an expected way and when it doesn't. 

If have a function (a check) and I call it and it can't execute because a dependency is missing, how does that account to  completing in an expected way?

> The benefit for users is that overtime they'll know that an ERROR result is something that's beyond their control, unlike all the other check results.

As I stated above, you require a very specific type of user/scenario that has control over that type of ERROR, for less powerful/enabled/skilled users, having a FAIL that they can't fix on their own in the font can be frustrating.

Consider another example, the conversation between a client and their foundry: the client requires by contract from the foundry to fix all FAILS (make *bakery *profile pass) but the incomplete system setup of the client can't be fixed by the foundry. I imagine a lot of emails going back and forth until the product manager on the client side has fixed their setup, requiring attention/work from everyone involved.

**Comment by miguelsousa** [comment]
@graphicore Thank you for the input. Appreciated.

> If have a function (a check) and I call it and it can't execute because a dependency is missing, how does that account to completing in an expected way?

By "expected way" I meant that a check yields a known code (e.g. `fontval-not-available`, `fontval-returned-error`) instead of a traceback dump.

**Comment by felipesanches** [comment]
@miguelsousa, this merged PR changes the previously established semantic distinction between the **FAIL** and **ERROR** status codes.  I agree that there are some aspects of the code-base that may have caused confusion regarding those meanings (such as that user message on the terminal reporter and that vendor-specific override) and I am willing to amend those to remove any remaining ambiguity.

It is my intention to minimize the differences between the Font Bakery repository and your personal fork of it, in the hope that we'll soon get back to collaboration on a shared repository. For that reason, I'd like to ask you to reconsider this change or, alternatively, to open an issue in which you could propose and discuss this semantic change with the wider user/developer community.

**Comment by miguelsousa** [comment]
> open an issue in which you could propose and discuss this semantic change with the wider user/developer community

Will do. Allow me some time to put it together.
